# Generated by Django 5.1.4 on 2024-12-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('state', models.CharField(choices=[('safe', 'Safe'), ('natural_disaster_incoming', 'Natural disaster incoming'), ('natural_disaster_ongoing', 'Natural disaster ongoing'), ('natural_disaster_ended', 'Natural disaster ended')], default='safe', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NaturalDisasterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('todo_list', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NaturalDisasterInCityModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_app.citymodel')),
                ('natural_disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_app.naturaldisastermodel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency_app.citymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
