# Generated by Django 5.1.4 on 2024-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturaldisastermodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
