# Generated by Django 5.1.4 on 2025-01-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0003_district_districtcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NaturalDisasterModel',
            new_name='NaturalDisaster',
        ),
        migrations.DeleteModel(
            name='DistrictCode',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.IntegerField(default=1602, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
