# Generated by Django 5.1.4 on 2025-01-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0004_rename_naturaldisastermodel_naturaldisaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(default='1602', max_length=4, primary_key=True, serialize=False),
        ),
    ]
