# Generated by Django 5.1.4 on 2025-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0005_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NaturalDisasterModel',
            new_name='NaturalDisaster',
        ),
        migrations.DeleteModel(
            name='DistrictCode',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.TextField(default='1602', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
