# Generated by Django 5.1.4 on 2025-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0005_alter_district_district_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.TextField(default='1602', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
