# Generated by Django 5.1.4 on 2025-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0006_rename_naturaldisastermodel_naturaldisaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
