# Generated by Django 5.1.4 on 2025-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0006_alter_district_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.TextField(default='1602', primary_key=True, serialize=False),
        ),
    ]
