# Generated by Django 5.1.3 on 2025-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0007_alter_district_district_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AddField(
            model_name='user',
            name='districts',
            field=models.ManyToManyField(blank=True, to='emergency_app.district'),
        ),
    ]
