# Generated by Django 5.1.4 on 2025-02-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0008_remove_user_district_user_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_list', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('disaster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_app.naturaldisaster')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
